using System;
using System.Collections.Generic;
using System.IO;

namespace ADIapp.Services;

public static class LanguageService
{
    private static readonly string SettingsFilePath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
        "ADIapp",
        "language.txt"
    );

    public static string CurrentLanguage { get; private set; } = LoadSavedLanguage();

    public static event Action? LanguageChanged;

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Settings_Title"] = "Settings",
            ["Settings_Language"] = "Language",
            ["Sidebar_Home"] = "Home",
            ["Sidebar_Settings"] = "Settings",
            ["Sidebar_Tickets"] = "Tickets",
            ["Sidebar_Notifications"] = "Notifications",
            ["Sidebar_Info"] = "Info",
            ["Sidebar_Logout"] = "Logout",
            ["Sidebar_LicenseExp"] = "License Expiration",
            ["Home_Welcome"] = "Welcome to\nADI Performance",
            ["Home_Desc"] = "Next-generation ECU tuning,\nfile service management and automotive performance diagnostics.",
            ["Home_GetStarted"] = "Get Started ➔",
            ["Home_LearnMore"] = "📖 How It Works",
            ["Home_QuickAccess"] = "Quick Access",
            ["Home_QuickAccessDesc"] = "Explore core tools and manage your performance files",
            ["Home_EcuTuning"] = "ECU Tuning Service",
            ["Home_EcuDesc"] = "Upload original ECU files and request custom remaps for Stage 1, Stage 2, DPF & EGR solutions.",
            ["Home_SupportTickets"] = "Support & Tickets",
            ["Home_SupportDesc"] = "Communicate directly with our master engineers for custom modifications and technical assistance.",
            ["Home_PlatformInfo"] = "Platform Information",
            ["Home_PlatformDesc"] = "Check active license details, hardware compatibility, and platform documentation.",
            ["TopPanel_Hello"] = "Hello,",
            ["TopPanel_Token"] = "Token:",
            ["TopPanel_Account"] = "Account",
            ["TopPanel_Logout"] = "Logout",
            ["TopPanel_Notifications"] = "Notifications",
            ["TopPanel_ClearAll"] = "Clear All",
            ["TopPanel_SeeAll"] = "See All Notifications ➔",
            ["TopPanel_TokenMenu"] = "Token Balance",
            ["Orders_Title"] = "Orders",
            ["Orders_Subtitle"] = "Track past tuning orders, completed/canceled files, and pending ECU support requests.",
            ["Notifications_Title"] = "Notifications & Alerts",
            ["Notifications_Subtitle"] = "View and manage all system updates, order alerts, and messages.",
            ["Notifications_MarkAll"] = "Mark All Read",
            ["Notifications_NoNotifs"] = "No notifications yet",
            ["Logout_Title"] = "Log Out",
            ["Logout_Message"] = "Are you sure you want to log out? You will need to sign back in to access your account.",
            ["Logout_Cancel"] = "Cancel",
            ["Logout_Confirm"] = "Log Out",
            ["Login_Welcome"] = "Welcome Back",
            ["Login_Subtitle"] = "Sign in to access your ADI Performance account",
            ["Login_Username"] = "Username or Email",
            ["Login_Password"] = "Password",
            ["Login_Submit"] = "Sign In ➔",
            ["Login_SigningIn"] = "Signing in...",
            ["Login_NoAccount"] = "Don't have an account? Sign Up",
            ["Login_PasswordPlaceholder"] = "Enter password",
            ["Login_UsernamePlaceholder"] = "Enter username or email",
            ["Account_Title"] = "Account Profile",
            ["Account_Subtitle"] = "Manage your personal information and contact details",
            ["Account_FirstName"] = "First name",
            ["Account_LastName"] = "Last name",
            ["Account_Email"] = "Email address",
            ["Account_Phone"] = "Phone number",
            ["Account_Save"] = "Save Changes",
            ["Token_Title"] = "Token Credits",
            ["Token_Subtitle"] = "Your current available service tokens balance",
            ["Token_AvailableBalance"] = "Available Balance",
            ["Info_Badge"] = "HOW IT WORKS",
            ["Info_Title"] = "How To Use ADI Performance",
            ["Info_Subtitle"] = "4 simple steps to tune and modify your vehicle file in seconds",
            ["Info_Step1_Title"] = "📁 Upload Your File",
            ["Info_Step1_Desc"] = "Click New Upload on the left sidebar and choose your original vehicle binary file.",
            ["Info_Step2_Title"] = "🔍 Instant Vehicle Check",
            ["Info_Step2_Desc"] = "Our system automatically detects your vehicle specs, engine displacement, and ECU info.",
            ["Info_Step3_Title"] = "⚡ Select Options",
            ["Info_Step3_Desc"] = "Toggle your desired performance stages, delete options, or special features with 1 click.",
            ["Info_Step4_Title"] = "💾 Save & Download",
            ["Info_Step4_Desc"] = "Click Save Order to confirm your selection and download your ready-to-use tuned file!",
            ["Info_UnderstandBtn"] = "I Understand ➔",
            ["Info_Website"] = "Our Website",
            ["Info_Updates"] = "Updates",
            ["Info_News"] = "News & Portal",
            ["Info_Phone"] = "Phone Support",
            ["Ticket_Title"] = "Support Tickets & Messages",
            ["Ticket_Subtitle"] = "Communicate directly with technical support regarding ECU additions and orders.",
            ["Ticket_Placeholder"] = "Type your support message...",
            ["Ticket_Send"] = "Send Message",
            ["Settings_Subtitle"] = "Customize application preferences and display language",
            ["Tune_Title"] = "Vehicle & ECU Information",
            ["Tune_Subtitle"] = "Upload a binary file or select an active task to inspect specifications.",
            ["Tune_Back"] = "← Back",
            ["Tune_ActiveTasks"] = "Active Tasks",
            ["Tune_NewUpload"] = "+ New Upload",
            ["Tune_NoActiveTasks"] = "No active tasks",
            ["Tune_VehSpecs"] = "VEHICLE SPECS",
            ["Tune_Producer"] = "PRODUCER",
            ["Tune_Model"] = "MODEL",
            ["Tune_YearChassis"] = "YEAR / CHASSIS",
            ["Tune_BuildType"] = "BUILD / TYPE",
            ["Tune_EngSpecs"] = "ENGINE SPECS",
            ["Tune_NameType"] = "NAME / TYPE",
            ["Tune_Displacement"] = "DISPLACEMENT",
            ["Tune_Output"] = "OUTPUT (PS / KW)",
            ["Tune_Emission"] = "EMISSION",
            ["Tune_Transmission"] = "TRANSMISSION",
            ["Tune_EcuSpecs"] = "ECU SPECS",
            ["Tune_ProdBuild"] = "PRODUCER / BUILD",
            ["Tune_HwNr"] = "STAGE / HW NR",
            ["Tune_ProdNr"] = "PART / PROD NR",
            ["Tune_SwVersion"] = "SW VERSION",
            ["Tune_SwSize"] = "SW SIZE",
            ["Tune_AvailableTunes"] = "AVAILABLE DATABASE TUNES & MODIFICATIONS",
            ["Tune_OriginalFile"] = "Original file",
            ["Tune_Save"] = "Save",
            ["Tune_SelectEcuFile"] = "📁 Select ECU File to Upload",
            ["Tune_OrderSelected"] = "Order Selected Tuning Services",
            ["Tune_Selected"] = "Selected",
            ["Tune_FilterAll"] = "All Options",
            ["Tune_FilterPerf"] = "🚀 Performance",
            ["Tune_FilterDeletes"] = "🛡️ Deletes",
            ["Tune_FilterFeatures"] = "⚡ Special Features"
        },
        ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Settings_Title"] = "Paramètres",
            ["Settings_Language"] = "Langue",
            ["Sidebar_Home"] = "Accueil",
            ["Sidebar_Settings"] = "Paramètres",
            ["Sidebar_Tickets"] = "Support",
            ["Sidebar_Info"] = "À propos",
            ["Sidebar_Logout"] = "Déconnexion",
            ["Sidebar_LicenseExp"] = "Expiration de licence",
            ["Home_Welcome"] = "Bienvenue sur\nADI Performance",
            ["Home_Desc"] = "Service de reprogrammation ECU nouvelle génération,\ngestion de fichiers et diagnostic automobile.",
            ["Home_GetStarted"] = "Commencer ➔",
            ["Home_LearnMore"] = "📖 Comment ça marche",
            ["Home_QuickAccess"] = "Accès Rapide",
            ["Home_QuickAccessDesc"] = "Explorez les outils principaux et gérez vos fichiers de performance",
            ["Home_EcuTuning"] = "Service Tuning ECU",
            ["Home_EcuDesc"] = "Téléchargez vos fichiers ECU originaux et demandez des cartographies sur mesure (Stage 1, Stage 2, DPF & EGR).",
            ["Home_SupportTickets"] = "Support & Tickets",
            ["Home_SupportDesc"] = "Communiquez directement avec nos ingénieurs pour vos demandes spécifiques et assistance technique.",
            ["Home_PlatformInfo"] = "Informations Plateforme",
            ["Home_PlatformDesc"] = "Vérifiez votre licence active, la compatibilité matérielle et la documentation.",
            ["TopPanel_Hello"] = "Bonjour,",
            ["TopPanel_Token"] = "Jetons :",
            ["TopPanel_Account"] = "Mon Compte",
            ["TopPanel_Logout"] = "Déconnexion",
            ["TopPanel_Notifications"] = "Notifications",
            ["TopPanel_ClearAll"] = "Tout effacer",
            ["TopPanel_SeeAll"] = "Voir toutes les notifications ➔",
            ["TopPanel_TokenMenu"] = "Solde Jetons",
            ["Orders_Title"] = "Commandes",
            ["Orders_Subtitle"] = "Suivez vos commandes de reprogrammation passées et demandes de support ECU.",
            ["Notifications_Title"] = "Notifications & Alertes",
            ["Notifications_Subtitle"] = "Consultez et gérez toutes les mises à jour système et alertes.",
            ["Notifications_MarkAll"] = "Tout marquer comme lu",
            ["Notifications_NoNotifs"] = "Aucune notification",
            ["Logout_Title"] = "Déconnexion",
            ["Logout_Message"] = "Êtes-vous sûr de vouloir vous déconnecter ? Vous devrez vous réauthentifier pour accéder à votre compte.",
            ["Logout_Cancel"] = "Annuler",
            ["Logout_Confirm"] = "Se déconnecter",
            ["Login_Welcome"] = "Bienvenue",
            ["Login_Subtitle"] = "Connectez-vous à votre compte ADI Performance",
            ["Login_Username"] = "Nom d'utilisateur ou e-mail",
            ["Login_Password"] = "Mot de passe",
            ["Login_Submit"] = "Se connecter ➔",
            ["Login_SigningIn"] = "Connexion...",
            ["Login_NoAccount"] = "Vous n'avez pas de compte ? S'inscrire",
            ["Login_PasswordPlaceholder"] = "Entrez votre mot de passe",
            ["Login_UsernamePlaceholder"] = "Entrez votre nom d'utilisateur ou e-mail",
            ["Account_Title"] = "Profil du Compte",
            ["Account_Subtitle"] = "Gérez vos informations personnelles et vos coordonnées",
            ["Account_FirstName"] = "Prénom",
            ["Account_LastName"] = "Nom",
            ["Account_Email"] = "Adresse e-mail",
            ["Account_Phone"] = "Numéro de téléphone",
            ["Account_Save"] = "Enregistrer les modifications",
            ["Token_Title"] = "Crédits Jetons",
            ["Token_Subtitle"] = "Votre solde actuel de jetons de service disponibles",
            ["Token_AvailableBalance"] = "Solde Disponible",
            ["Info_Badge"] = "COMMENT ÇA MARCHE",
            ["Info_Title"] = "Comment utiliser ADI Performance",
            ["Info_Subtitle"] = "4 étapes simples pour reprogrammer votre fichier véhicule en quelques secondes",
            ["Info_Step1_Title"] = "📁 Téléchargez votre fichier",
            ["Info_Step1_Desc"] = "Cliquez sur Nouveau Fichier dans le menu de gauche et choisissez votre fichier binaire d'origine.",
            ["Info_Step2_Title"] = "🔍 Détection automatique",
            ["Info_Step2_Desc"] = "Notre système détecte automatiquement les données de votre véhicule et du calculateur.",
            ["Info_Step3_Title"] = "⚡ Sélectionnez vos options",
            ["Info_Step3_Desc"] = "Activez vos stages de puissance, suppressions d'options ou options spéciales en 1 clic.",
            ["Info_Step4_Title"] = "💾 Validez et Téléchargez",
            ["Info_Step4_Desc"] = "Cliquez sur Enregistrer pour valider votre commande et télécharger votre fichier prêt à l'emploi !",
            ["Info_UnderstandBtn"] = "J'ai compris ➔",
            ["Info_Website"] = "Notre Site Web",
            ["Info_Updates"] = "Mises à jour",
            ["Info_News"] = "Actualités & Portail",
            ["Info_Phone"] = "Support Téléphonique",
            ["Ticket_Title"] = "Tickets de Support & Messages",
            ["Ticket_Subtitle"] = "Communiquez directement avec le support technique pour les ajouts d'ECU et commandes.",
            ["Ticket_Placeholder"] = "Tapez votre message de support...",
            ["Ticket_Send"] = "Envoyer le message",
            ["Settings_Subtitle"] = "Personnalisez les préférences de l'application et la langue d'affichage",
            ["Tune_Title"] = "Informations Véhicule & ECU",
            ["Tune_Subtitle"] = "Téléchargez un fichier binaire ou sélectionnez une tâche pour inspecter ses spécifications.",
            ["Tune_Back"] = "← Retour",
            ["Tune_ActiveTasks"] = "Tâches Actives",
            ["Tune_NewUpload"] = "+ Télécharger un fichier",
            ["Tune_NoActiveTasks"] = "Aucune tâche active",
            ["Tune_VehSpecs"] = "SPÉCIFICATIONS VÉHICULE",
            ["Tune_Producer"] = "CONSTRUCTEUR",
            ["Tune_Model"] = "MODÈLE",
            ["Tune_YearChassis"] = "ANNÉE / CHÂSSIS",
            ["Tune_BuildType"] = "FINITION / TYPE",
            ["Tune_EngSpecs"] = "SPÉCIFICATIONS MOTEUR",
            ["Tune_NameType"] = "CODE / TYPE",
            ["Tune_Displacement"] = "CYLINDRÉE",
            ["Tune_Output"] = "PUISSANCE (CH / KW)",
            ["Tune_Emission"] = "NORME POLLUTION",
            ["Tune_Transmission"] = "BOÎTE DE VITESSES",
            ["Tune_EcuSpecs"] = "SPÉCIFICATIONS CALCULATEUR",
            ["Tune_ProdBuild"] = "FABRICANT / MODÈLE",
            ["Tune_HwNr"] = "STAGE / RÉF HW",
            ["Tune_ProdNr"] = "NUMÉRO PIÈCE",
            ["Tune_SwVersion"] = "VERSION SOFTWARE",
            ["Tune_SwSize"] = "TAILLE SOFTWARE",
            ["Tune_AvailableTunes"] = "CARTOGRAPHIES & OPTIONS DISPONIBLES",
            ["Tune_OriginalFile"] = "Fichier Original",
            ["Tune_Save"] = "Enregistrer",
            ["Tune_SelectEcuFile"] = "📁 Sélectionner un fichier ECU à télécharger",
            ["Tune_OrderSelected"] = "Commander les services sélectionnés",
            ["Tune_Selected"] = "Sélectionné(s)",
            ["Tune_FilterAll"] = "Toutes les options",
            ["Tune_FilterPerf"] = "🚀 Performance",
            ["Tune_FilterDeletes"] = "🛡️ Suppressions",
            ["Tune_FilterFeatures"] = "⚡ Options spéciales"
        },
        ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Settings_Title"] = "Configuración",
            ["Settings_Language"] = "Idioma",
            ["Sidebar_Home"] = "Inicio",
            ["Sidebar_Settings"] = "Configuración",
            ["Sidebar_Tickets"] = "Soporte",
            ["Sidebar_Notifications"] = "Notificaciones",
            ["Sidebar_Info"] = "Información",
            ["Sidebar_Logout"] = "Cerrar sesión",
            ["Sidebar_LicenseExp"] = "Expiración de Licencia",
            ["Home_Welcome"] = "Bienvenido a\nADI Performance",
            ["Home_Desc"] = "Reprogramación de ECU de última generación,\ngestión de archivos y diagnóstico de rendimiento automotriz.",
            ["Home_GetStarted"] = "Comenzar ➔",
            ["Home_LearnMore"] = "📖 Cómo Funciona",
            ["Home_QuickAccess"] = "Acceso Rápido",
            ["Home_QuickAccessDesc"] = "Explora herramientas principales y gestiona tus archivos de rendimiento",
            ["Home_EcuTuning"] = "Servicio de Reprogramación ECU",
            ["Home_EcuDesc"] = "Sube archivos originales de ECU y solicita reprogramaciones personalizadas para Stage 1, Stage 2, DPF y EGR.",
            ["Home_SupportTickets"] = "Soporte y Tickets",
            ["Home_SupportDesc"] = "Comunícate directamente con nuestros ingenieros maestros para modificaciones personalizadas y asistencia técnica.",
            ["Home_PlatformInfo"] = "Información de la Plataforma",
            ["Home_PlatformDesc"] = "Consulta detalles de licencia activa, compatibilidad de hardware y documentación de la plataforma.",
            ["TopPanel_Hello"] = "Hola,",
            ["TopPanel_Token"] = "Fichas:",
            ["TopPanel_Account"] = "Mi Cuenta",
            ["TopPanel_Logout"] = "Cerrar sesión",
            ["TopPanel_Notifications"] = "Notificaciones",
            ["TopPanel_ClearAll"] = "Borrar todo",
            ["TopPanel_SeeAll"] = "Ver todas las notificaciones ➔",
            ["TopPanel_TokenMenu"] = "Saldo de Fichas",
            ["Orders_Title"] = "Pedidos",
            ["Orders_Subtitle"] = "Rastrea pedidos de reprogramación pasados, archivos completados/cancelados y solicitudes pendientes.",
            ["Notifications_Title"] = "Notificaciones y Alertas",
            ["Notifications_Subtitle"] = "Consulta y gestiona las actualizaciones del sistema, alertas de pedidos y mensajes.",
            ["Notifications_MarkAll"] = "Marcar todo como leído",
            ["Notifications_NoNotifs"] = "Aún no hay notificaciones",
            ["Logout_Title"] = "Cerrar Sesión",
            ["Logout_Message"] = "¿Estás seguro de que deseas cerrar sesión? Tendrás que iniciar sesión nuevamente para acceder a tu cuenta.",
            ["Logout_Cancel"] = "Cancelar",
            ["Logout_Confirm"] = "Cerrar Sesión",
            ["Login_Welcome"] = "Bienvenido de Nuevo",
            ["Login_Subtitle"] = "Inicia sesión para acceder a tu cuenta de ADI Performance",
            ["Login_Username"] = "Usuario o Correo",
            ["Login_Password"] = "Contraseña",
            ["Login_Submit"] = "Iniciar Sesión ➔",
            ["Login_SigningIn"] = "Iniciando sesión...",
            ["Login_NoAccount"] = "¿No tienes una cuenta? Regístrate",
            ["Login_PasswordPlaceholder"] = "Ingresa tu contraseña",
            ["Login_UsernamePlaceholder"] = "Ingresa usuario o correo",
            ["Account_Title"] = "Perfil de la Cuenta",
            ["Account_Subtitle"] = "Gestiona tu información personal y datos de contacto",
            ["Account_FirstName"] = "Nombre",
            ["Account_LastName"] = "Apellido",
            ["Account_Email"] = "Correo electrónico",
            ["Account_Phone"] = "Número de teléfono",
            ["Account_Save"] = "Guardar Cambios",
            ["Token_Title"] = "Créditos de Fichas",
            ["Token_Subtitle"] = "Tu saldo disponible actual de fichas de servicio",
            ["Token_AvailableBalance"] = "Saldo Disponible",
            ["Info_Badge"] = "CÓMO FUNCIONA",
            ["Info_Title"] = "Cómo Usar ADI Performance",
            ["Info_Subtitle"] = "4 sencillos pasos para reprogramar tu archivo de vehículo en segundos",
            ["Info_Step1_Title"] = "📁 Sube tu Archivo",
            ["Info_Step1_Desc"] = "Haz clic en Nuevo Archivo en la barra lateral e ingresa tu archivo binario original.",
            ["Info_Step2_Title"] = "🔍 Verificación Instantánea",
            ["Info_Step2_Desc"] = "Nuestro sistema detecta automáticamente las especificaciones de tu vehículo y la ECU.",
            ["Info_Step3_Title"] = "⚡ Selecciona Opciones",
            ["Info_Step3_Desc"] = "Activa tus stages de rendimiento, eliminaciones o funciones especiales con 1 clic.",
            ["Info_Step4_Title"] = "💾 Guarda y Descarga",
            ["Info_Step4_Desc"] = "Haz clic en Guardar Pedido para confirmar tu selección y descargar tu archivo listo para usar.",
            ["Info_UnderstandBtn"] = "Entendido ➔",
            ["Info_Website"] = "Sitio Web",
            ["Info_Updates"] = "Actualizaciones",
            ["Info_News"] = "Noticias y Portal",
            ["Info_Phone"] = "Soporte Telefónico",
            ["Ticket_Title"] = "Tickets de Soporte y Mensajes",
            ["Ticket_Subtitle"] = "Comunícate directamente con el soporte técnico para adiciones de ECU y pedidos.",
            ["Ticket_Placeholder"] = "Escribe tu mensaje de soporte...",
            ["Ticket_Send"] = "Enviar Mensaje",
            ["Settings_Subtitle"] = "Personaliza las preferencias de la aplicación y el idioma de pantalla",
            ["Tune_Title"] = "Información del Vehículo y ECU",
            ["Tune_Subtitle"] = "Sube un archivo binario o selecciona una tarea activa para inspeccionar especificaciones.",
            ["Tune_Back"] = "← Volver",
            ["Tune_ActiveTasks"] = "Tareas Activas",
            ["Tune_NewUpload"] = "+ Nuevo Archivo",
            ["Tune_NoActiveTasks"] = "Sin tareas activas",
            ["Tune_VehSpecs"] = "ESPECIFICACIONES DEL VEHÍCULO",
            ["Tune_Producer"] = "FABRICANTE",
            ["Tune_Model"] = "MODELO",
            ["Tune_YearChassis"] = "AÑO / CHASIS",
            ["Tune_BuildType"] = "MONTAJE / TIPO",
            ["Tune_EngSpecs"] = "ESPECIFICACIONES DEL MOTOR",
            ["Tune_NameType"] = "NOMBRE / TIPO",
            ["Tune_Displacement"] = "CILINDRADA",
            ["Tune_Output"] = "POTENCIA (CV / KW)",
            ["Tune_Emission"] = "EMISIONES",
            ["Tune_Transmission"] = "TRANSMISIÓN",
            ["Tune_EcuSpecs"] = "ESPECIFICACIONES DE ECU",
            ["Tune_ProdBuild"] = "FABRICANTE / MODELO",
            ["Tune_HwNr"] = "STAGE / REF HW",
            ["Tune_ProdNr"] = "Nº PIEZA / PROD",
            ["Tune_SwVersion"] = "VERSIÓN DE SOFTWARE",
            ["Tune_SwSize"] = "TAMAÑO DE SOFTWARE",
            ["Tune_AvailableTunes"] = "MODIFICACIONES Y MAPAS DISPONIBLES EN BASE DE DATOS",
            ["Tune_OriginalFile"] = "Archivo Original",
            ["Tune_Save"] = "Guardar",
            ["Tune_SelectEcuFile"] = "📁 Seleccionar archivo ECU para cargar",
            ["Tune_OrderSelected"] = "Pedir servicios seleccionados",
            ["Tune_Selected"] = "Seleccionado(s)",
            ["Tune_FilterAll"] = "Todas las opciones",
            ["Tune_FilterPerf"] = "🚀 Rendimiento",
            ["Tune_FilterDeletes"] = "🛡️ Eliminaciones",
            ["Tune_FilterFeatures"] = "⚡ Funciones especiales"
        },
        ["de"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Settings_Title"] = "Einstellungen",
            ["Settings_Language"] = "Sprache",
            ["Sidebar_Home"] = "Startseite",
            ["Sidebar_Settings"] = "Einstellungen",
            ["Sidebar_Tickets"] = "Support",
            ["Sidebar_Notifications"] = "Benachrichtigungen",
            ["Sidebar_Info"] = "Informationen",
            ["Sidebar_Logout"] = "Abmelden",
            ["Sidebar_LicenseExp"] = "Lizenz-Ablaufdatum",
            ["Home_Welcome"] = "Willkommen bei\nADI Performance",
            ["Home_Desc"] = "ECU-Tuning der nächsten Generation,\nDateiverwaltung und Fahrzeug-Performancediagnose.",
            ["Home_GetStarted"] = "Jetzt Starten ➔",
            ["Home_LearnMore"] = "📖 Wie es funktioniert",
            ["Home_QuickAccess"] = "Schnellzugriff",
            ["Home_QuickAccessDesc"] = "Erkunden Sie Kern-Tools und verwalten Sie Ihre Leistungsdateien",
            ["Home_EcuTuning"] = "ECU-Tuning-Service",
            ["Home_EcuDesc"] = "Laden Sie originale ECU-Dateien hoch und fordern Sie maßgeschneiderte Kennfelder für Stage 1, Stage 2, DPF- & EGR-Lösungen an.",
            ["Home_SupportTickets"] = "Support & Tickets",
            ["Home_SupportDesc"] = "Kommunizieren Sie direkt mit unseren Chefingenieuren für individuelle Anpassungen und technische Hilfe.",
            ["Home_PlatformInfo"] = "Plattform-Informationen",
            ["Home_PlatformDesc"] = "Überprüfen Sie aktive Lizenzdetails, Hardware-Kompatibilität und Dokumentation.",
            ["TopPanel_Hello"] = "Hallo,",
            ["TopPanel_Token"] = "Token:",
            ["TopPanel_Account"] = "Mein Konto",
            ["TopPanel_Logout"] = "Abmelden",
            ["TopPanel_Notifications"] = "Benachrichtigungen",
            ["TopPanel_ClearAll"] = "Alle löschen",
            ["TopPanel_SeeAll"] = "Alle Benachrichtigungen anzeigen ➔",
            ["TopPanel_TokenMenu"] = "Token-Guthaben",
            ["Orders_Title"] = "Bestellungen",
            ["Orders_Subtitle"] = "Verfolgen Sie vergangene Tuning-Bestellungen, abgeschlossene/stornierte Dateien und ausstehende ECU-Anfragen.",
            ["Notifications_Title"] = "Benachrichtigungen & Hinweise",
            ["Notifications_Subtitle"] = "Verwalten Sie alle Systemaktualisierungen, Bestellhinweise und Nachrichten.",
            ["Notifications_MarkAll"] = "Alle als gelesen markieren",
            ["Notifications_NoNotifs"] = "Noch keine Benachrichtigungen",
            ["Logout_Title"] = "Abmelden",
            ["Logout_Message"] = "Sind Sie sicher, dass Sie sich abmelden möchten? Sie müssen sich erneut anmelden, um auf Ihr Konto zuzugreifen.",
            ["Logout_Cancel"] = "Abbrechen",
            ["Logout_Confirm"] = "Abmelden",
            ["Login_Welcome"] = "Willkommen zurück",
            ["Login_Subtitle"] = "Melden Sie sich an, um auf Ihr ADI Performance Konto zuzugreifen",
            ["Login_Username"] = "Benutzername oder E-Mail",
            ["Login_Password"] = "Passwort",
            ["Login_Submit"] = "Anmelden ➔",
            ["Login_SigningIn"] = "Anmeldung läuft...",
            ["Login_NoAccount"] = "Noch kein Konto? Registrieren",
            ["Login_PasswordPlaceholder"] = "Passwort eingeben",
            ["Login_UsernamePlaceholder"] = "Benutzername oder E-Mail eingeben",
            ["Account_Title"] = "Kontoprofil",
            ["Account_Subtitle"] = "Verwalten Sie Ihre persönlichen Informationen und Kontaktdaten",
            ["Account_FirstName"] = "Vorname",
            ["Account_LastName"] = "Nachname",
            ["Account_Email"] = "E-Mail-Adresse",
            ["Account_Phone"] = "Telefonnummer",
            ["Account_Save"] = "Änderungen speichern",
            ["Token_Title"] = "Token-Guthaben",
            ["Token_Subtitle"] = "Ihr aktuelles Guthaben an verfügbaren Service-Tokens",
            ["Token_AvailableBalance"] = "Verfügbares Guthaben",
            ["Info_Badge"] = "WIE ES FUNKTIONIERT",
            ["Info_Title"] = "So nutzen Sie ADI Performance",
            ["Info_Subtitle"] = "4 einfache Schritte, um Ihre Fahrzeugdatei in Sekundenschnelle anzupassen",
            ["Info_Step1_Title"] = "📁 Datei hochladen",
            ["Info_Step1_Desc"] = "Klicken Sie in der linken Seitenleiste auf Neue Datei und wählen Sie Ihre originale Binärdatei.",
            ["Info_Step2_Title"] = "🔍 Automatische Prüfung",
            ["Info_Step2_Desc"] = "Unser System erkennt automatisch Ihre Fahrzeugdaten, den Hubraum und die ECU-Info.",
            ["Info_Step3_Title"] = "⚡ Optionen auswählen",
            ["Info_Step3_Desc"] = "Aktivieren Sie Ihre gewünschten Leistungsstufen, Deaktivierungen oder Spezialfunktionen mit 1 Klick.",
            ["Info_Step4_Title"] = "💾 Speichern & Herunterladen",
            ["Info_Step4_Desc"] = "Klicken Sie auf Bestellung speichern, um Ihre Auswahl zu bestätigen und Ihre fertige Datei herunterzuladen!",
            ["Info_UnderstandBtn"] = "Verstanden ➔",
            ["Info_Website"] = "Unsere Website",
            ["Info_Updates"] = "Updates",
            ["Info_News"] = "News & Portal",
            ["Info_Phone"] = "Telefon-Support",
            ["Ticket_Title"] = "Support-Tickets & Nachrichten",
            ["Ticket_Subtitle"] = "Kommunizieren Sie direkt mit dem technischen Support bezüglich ECU-Erweiterungen und Bestellungen.",
            ["Ticket_Placeholder"] = "Geben Sie Ihre Support-Nachricht ein...",
            ["Ticket_Send"] = "Nachricht senden",
            ["Settings_Subtitle"] = "Passen Sie die Anwendungseinstellungen und die Anzeigesprache an",
            ["Tune_Title"] = "Fahrzeug- & ECU-Informationen",
            ["Tune_Subtitle"] = "Laden Sie eine Binärdatei hoch oder wählen Sie eine aktive Aufgabe, um Spezifikationen zu prüfen.",
            ["Tune_Back"] = "← Zurück",
            ["Tune_ActiveTasks"] = "Aktive Aufgaben",
            ["Tune_NewUpload"] = "+ Neue Datei",
            ["Tune_NoActiveTasks"] = "Keine aktiven Aufgaben",
            ["Tune_VehSpecs"] = "FAHRZEUGDATEN",
            ["Tune_Producer"] = "HERSTELLER",
            ["Tune_Model"] = "MODELL",
            ["Tune_YearChassis"] = "JAHR / FAHRGESTELL",
            ["Tune_BuildType"] = "AUFBAU / TYP",
            ["Tune_EngSpecs"] = "MOTORDATEN",
            ["Tune_NameType"] = "NAME / TYP",
            ["Tune_Displacement"] = "HUBRAUM",
            ["Tune_Output"] = "LEISTUNG (PS / KW)",
            ["Tune_Emission"] = "ABGASNORM",
            ["Tune_Transmission"] = "GETRIEBE",
            ["Tune_EcuSpecs"] = "ECU-SPEZIFIKATIONEN",
            ["Tune_ProdBuild"] = "HERSTELLER / MODELL",
            ["Tune_HwNr"] = "STAGE / HW-NR",
            ["Tune_ProdNr"] = "TEILE- / PROD-NR",
            ["Tune_SwVersion"] = "SOFTWARE-VERSION",
            ["Tune_SwSize"] = "SOFTWARE-GRÖSSE",
            ["Tune_AvailableTunes"] = "VERFÜGBARE DATENBANK-TUNINGS & MODIFIKATIONEN",
            ["Tune_OriginalFile"] = "Originaldatei",
            ["Tune_Save"] = "Speichern",
            ["Tune_SelectEcuFile"] = "📁 ECU-Datei zum Hochladen auswählen",
            ["Tune_OrderSelected"] = "Ausgewählte Tuning-Services bestellen",
            ["Tune_Selected"] = "Ausgewählt",
            ["Tune_FilterAll"] = "Alle Optionen",
            ["Tune_FilterPerf"] = "🚀 Leistung",
            ["Tune_FilterDeletes"] = "🛡️ Deaktivierungen",
            ["Tune_FilterFeatures"] = "⚡ Spezialfunktionen"
        }
    };

    public static string Get(string key)
    {
        if (Translations.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            return val;

        if (Translations["en"].TryGetValue(key, out var fallback))
            return fallback;

        return key;
    }

    private static string LoadSavedLanguage()
    {
        try
        {
            if (File.Exists(SettingsFilePath))
            {
                string saved = File.ReadAllText(SettingsFilePath).Trim().ToLowerInvariant();
                if (saved == "fr" || saved == "en" || saved == "es" || saved == "de")
                    return saved;
            }
        }
        catch { }
        return "en";
    }

    public static void SetLanguage(string langCode)
    {
        langCode = langCode.ToLowerInvariant();
        if (langCode != "en" && langCode != "fr" && langCode != "es" && langCode != "de")
            langCode = "en";

        if (CurrentLanguage != langCode)
        {
            CurrentLanguage = langCode;
            SaveLanguage(langCode);
            LanguageChanged?.Invoke();
        }
    }

    private static void SaveLanguage(string langCode)
    {
        try
        {
            string? dir = Path.GetDirectoryName(SettingsFilePath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }
            File.WriteAllText(SettingsFilePath, langCode);
        }
        catch { }
    }
}
